spring.application.name=java-log-service
server.servlet.context-path=/api/java

spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health
management.endpoints.web.base-path=/
