spring.application.name=java-log-service
server.servlet.context-path=/api/java

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.defer-datasource-initialization=true


spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health
management.endpoints.web.base-path=/
