spring.application.name=java-log-service
server.servlet.context-path=/api/java

# --- H2 Database Configuration (para desenvolvimento local) ---
# spring.h2.console.enabled=true
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# --- PostgreSQL Database Configuration (para produção na AWS) ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Esta linha garante que o data.sql (se existir) rode depois da criação das tabelas
spring.jpa.defer-datasource-initialization=true

# Esta linha diz ao Hibernate para criar/atualizar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
